name: canary

on:
    push:
        branches:
            - release-please-*
        paths:
            - "CHANGELOG.md"
    workflow_dispatch:

permissions:
    contents: write # for checkout and tag
    actions: write # updating envs
    pull-requests: write # for comments
    packages: write # for publish
    id-token: write


jobs:
    setup:
        runs-on: "ubuntu-latest"
        steps:
            -   uses: actions/checkout@v3
                name: Checkout [Pull Request]
                with:
                    # By default, PRs will be checked-out based on the Merge Commit, but we want the actual branch HEAD.
                    ref: ${{ github.event.pull_request.head.sha }}
                    # We need to fetch all branches and commits so that Nx affected has a base to compare against.
                    fetch-depth: 0

            - name: Commit Linter
              uses: wagoid/commitlint-github-action@v5.3.0

    main:
        name: Main Job
        needs:
            - setup
        uses: ./.github/workflows/node-job.yml
        secrets: inherit
        with:
            name: "Install Dependencies"
            command: ""
            ref: ${{ github.event.pull_request.head.sha }}

    parallel-jobs:
        name: Jobs
        needs:
            - main
        strategy:
            matrix:
                config:
                    -   name: Lint
                        command: 'yarn lint:all'
                    -   name: Test
                        command: 'yarn test:all --ci --coverage'

        uses: ./.github/workflows/node-job.yml
        secrets: inherit
        with:
            name: "${{ matrix.config.name }}"
            command: ${{ matrix.config.command }}
            ref: ${{ github.event.pull_request.head.sha }}

    publish:
        name: Publish
        needs:
            - 'main'
            - 'parallel-jobs'
        uses: ./.github/workflows/node-job.yml
        secrets: inherit
        with:
            name: "Publish [Canary]"
            command: 'yarn release:canary'
            ref: ${{ github.event.pull_request.head.sha }}

