name: "ci"

on:
    workflow_dispatch:
    push:
        branches-ignore:
            - "release-please-**"
            - "main"

permissions:
    contents: read # for checkout
    pull-requests: read # for comments
    actions: read

jobs:
    setup:
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Commit Linter
              uses: wagoid/commitlint-github-action@v5.3.0
    main:
        name: Nx Cloud - Main Job
        needs:
            - setup
        uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.2
        with:
            number-of-agents: 3
            init-commands: |
                yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
            parallel-commands: |
                yarn nx-cloud record -- yarn nx workspace-lint
            parallel-commands-on-agents: |
                yarn nx affected --target=lint --parallel=6
                yarn nx affected --target=test --parallel=6 --ci --coverage
                yarn nx affected --target=build --parallel=3

    agents:
        name: Nx Cloud - Agents
        needs:
            - setup
        uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.2
        with:
            number-of-agents: 3
