name: publish

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            publish:
                description: forces the SDK to build and publish
                type: boolean
                default: false

permissions:
    contents: write # for checkout and tag
    actions: write # updating envs
    pull-requests: write # for comments
    packages: write # for publish
    id-token: write

jobs:
    setup:
        runs-on: "ubuntu-latest"
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Commit Linter
              uses: wagoid/commitlint-github-action@v5.0.2

            - uses: google-github-actions/release-please-action@v3
              name: release-please
              id: release
              with:
                  token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
                  command: manifest
                  config-file: .github/release-please-config.json
                  manifest-file: .github/release-please-manifest.json
    publish:
        if: ${{ needs.setup.outputs.release_created == 'true' || inputs.publish }}
        runs-on: "ubuntu-latest"
        needs:
            - setup
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: "https://registry.npmjs.org"
                  token: ${{ secrets.NPM_PUSH_TOKEN }}

            - uses: nrwl/nx-set-shas@v3

            - name: bootstrap
              run: yarn bootstrap

            - name: build all
              run: yarn build:all

            - name: lint all
              run: yarn lint:all

            - name: test all
              run: yarn test:all

            - name: publish release
              run: |
                  yarn run release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUSH_TOKEN }}
