name: publish

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            publish:
                description: forces the SDK to build and publish
                type: boolean
                default: false

permissions:
    contents: write # for checkout and tag
    actions: write # updating envs
    pull-requests: write # for comments
    packages: write # for publish
    id-token: write

jobs:
    setup:
        runs-on: "ubuntu-latest"
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Commit Linter
              uses: wagoid/commitlint-github-action@v5.0.2

            - uses: google-github-actions/release-please-action@v3
              name: release-please
              id: release
              with:
                  token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
                  command: manifest
                  config-file: .github/release-please-config.json
                  manifest-file: .github/release-please-manifest.json

    main:
        name: Main Job
        if: ${{ needs.setup.outputs.release_created == 'true' || inputs.publish }}
        needs:
            - setup
        uses: ./.github/workflows/node-job.yml
        secrets: inherit
        with:
            name: "Install Dependencies"
            command: ""

    parallel-jobs:
        name: Jobs
        needs:
            - main
        strategy:
            matrix:
                config:
                    -   command: 'yarn lint:all'
                        name: Lint
                    -   command: 'yarn test:all --ci --coverage'
                        name: Test

        uses: ./.github/workflows/node-job.yml
        secrets: inherit
        with:
            name: "${{ matrix.config.name }}"
            command: ${{ matrix.config.command }}

    publish:
        name: Publish
        needs:
            - 'main'
            - 'parallel-jobs'
        uses: ./.github/workflows/node-job.yml
        secrets: inherit
        with:
            name: "Publish"
            command: 'yarn release'

